#pragma once
#include "texture.hpp"
#include "resource_defs.hpp"

/** Class which stores the posx, posy, scale, and rotation of a frame in an
 * animation, generated by the Animation class */
class AnimFrame {
public:
  TexHandle th;
  f32 posx;
  f32 posy;
  f32 scale;
  f32 rot;

  AnimFrame();
  AnimFrame(TexHandle th);
};
